version: '3.8'

services:
  # nginx:
  #   container_name: nginx
  #   hostname: nginx
  #   image: nginx:latest
  #   volumes:
  #     #- ./var/log/nginx:/var/log/nginx #log файлы.
  #     - /home/alex/server/etc/nginx/conf:/etc/nginx/conf.d:ro #Конфигурация nginx.
  #     #- ./etc/nginx/sites-enabled:/etc/nginx/sites-enabled:ro #Конфигурация площадок.
  #     #- ./volumes/etc/nginx/ssl:/etc/nginx/ssl:ro #сертификаты
  #     - ./etc/www/alexkomzzz.ml:/var/www/alexkomzzz.ml #Домашняя директория
  #     # - etc-letsencrypt:/etc/letsencrypt
  #     # - www-html:/var/www/certbot
  #   ports:
  #     - "80:80"
  #     #- "443:443"
  #   links:
  #     - go-api
  #   restart:
  #     always
  #   networks:
  #     net-server:
  #       ipv4_address: 172.16.1.4  
  db:
    image: postgres:latest
    restart: always
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - coll_tom:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    networks:
      net-server:
        ipv4_address: 172.16.2.3
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    networks:
      net-server:
        ipv4_address: 172.16.2.4
  go-api:
    build:
      context: .
      dockerfile: dockerfile.multi
    container_name: go-api
    hostname: go-api
    depends_on:
      - db
      - redis
    ports:
      - 8080:8080
    restart: always
    volumes:
      - file_tom:/web/files
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      net-server:
        ipv4_address: 172.16.2.2
  # certbot:
  #   image: certbot/certbot
  #   depends_on:
  #     - nginx
  #   container_name: certbot
  #   volumes:
  #     - etc-letsencrypt:/etc/letsencrypt
  #     - www-html:/var/www/certbot
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email komalex203@gmail.com --agree-tos --no-eff-email -d alexkomzzz.ml
  tlg-bot:
    image: telegram-bot/collect:latest
    container_name: tlg-bot
    hostname: tlg-bot
    depends_on:
      - go-api
    ports:
      - 9090:9090
    restart: always
    env_file:
      - .env
    # environment:
    #   - token="5807856069:AAH1IR4LxyR4v1RJ_srhRq9H_UggsnhEn_4"
    # volumes:
    #   - file_tom:/web/files
    networks:
      net-server:
        ipv4_address: 172.16.2.5
  
networks:
  net-server:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/24

volumes:
  coll_tom:
  file_tom:
#   www-html:
#   etc-letsencrypt: