port: ":8080"
host: "localhost"
GOOGLE_OAUTH_CLIENT_ID: "995350173631-6ffgi1nkh711d7g23dq7no9vgvl536r5.apps.googleusercontent.com"
YANDEX_OAUTH_CLIENT_ID: "fe3918e6e2ee4e68b1391c55e117ebc5"
domain: "localhost"

db:
  username: "postgres"
  password: "qwerty"
  host: "db"
  port: "5432"
  dbname: "postgres"